give @s createb:andesite_casing 32
give @s createb:cogwheel 16
give @s createb:shaft 32
give @s createb:gearbox 16
give @s createb:propeller 8
give @s createb:bearing 16
give @s createb:balloon_fabric 32
give @s createb:wrench 1
give @s createb:wind_bearing 8
give @s createb:propeller_controller 4
give @s createb:ballast_tank 16
give @s createb:large_cogwheel 8
give @s createb:clutch 8
give @s createb:gearshift 8
give @s createb:encased_fan 8
give @s createb:fluid_tank 8
give @s createb:mechanical_pump 8
give @s createb:steam_engine 8
give @s createb:rope_pulley 8
give @s createb:seat 8
give @s createb:chute 8
give @s createb:brass_funnel 8
give @s createb:andesite_funnel 8
give @s createb:redstone_link 8
give @s createb:boiler 8
give @s createb:elevator_pulley 8
give @s createb:deployer 4
give @s createb:mechanical_mixer 4
give @s createb:mechanical_press 4
give @s createb:crushing_wheel 4
give @s createb:millstone 4
give @s createb:spout 4
give @s createb:portable_storage_interface 4
give @s createb:nixie_tube 4
give @s createb:track_station 4
give @s createb:smart_chute 4
give @s createb:metal_girder 4
give @s createb:industrial_iron_block 4
give @s createb:copper_valve_handle 4
give @s createb:air_vent 4
give @s createb:mechanical_drill 2
give @s createb:mechanical_saw 2
give @s createb:mechanical_harvester 2
give @s createb:sequenced_gearshift 2
give @s createb:rotation_speed_controller 2
give @s createb:gantry_carriage 2
give @s createb:refined_radiator 2
give @s createb:sky_anchor 2
